language: node_js
node_js:
  - "lts/*"
  - "node"
install:
  - npm install
before_script:
  - npx --no-install greenkeeper-lockfile-update
script:
  - npm test
  - npm run codecov
after_script:
  - npx --no-install greenkeeper-lockfile-upload
